# Generated by Django 4.1.1 on 2024-02-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appinfo',
            fields=[
                ('infocode', models.AutoField(primary_key=True, serialize=False)),
                ('infovalue', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('created_on', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('modified_on', models.CharField(max_length=100)),
                ('modified_by', models.CharField(max_length=100)),
                ('dev_remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chemical_Master',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_no', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('project_code', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('created_on', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('modified_on', models.CharField(max_length=100)),
                ('modified_by', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('issue_date', models.CharField(max_length=100)),
                ('issue_to', models.CharField(max_length=100)),
                ('quantity_issued', models.CharField(max_length=100)),
                ('quantity_recieved', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
                ('dev_remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Tran',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('tran_type_IR', models.CharField(max_length=100)),
                ('qnty', models.CharField(max_length=100)),
                ('ref_number', models.CharField(max_length=100)),
                ('ref_type', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('created_on', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('modified_on', models.CharField(max_length=100)),
                ('modified_by', models.CharField(max_length=100)),
                ('quantity_issued', models.CharField(max_length=100)),
                ('quantity_recieved', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
                ('dev_remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IssuesNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('researcher_name', models.CharField(max_length=100)),
                ('issues_task', models.CharField(max_length=200)),
                ('date_time', models.DateField()),
                ('issue_raised_by', models.CharField(max_length=200)),
                ('issue_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoginCre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Master',
            fields=[
                ('project_code', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request_CI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ItemCode', models.CharField(max_length=100)),
                ('ItemType', models.CharField(max_length=100)),
                ('ItemName', models.CharField(max_length=100)),
                ('RequestDate', models.DateField()),
                ('RequestStatus', models.CharField(max_length=100)),
                ('RequestedBy', models.CharField(max_length=100)),
                ('RequestDetails', models.CharField(max_length=100)),
                ('ApprovedBy', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpDet',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app.project_master')),
            ],
        ),
    ]
