# Generated by Django 4.1.1 on 2024-01-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appinfo',
            fields=[
                ('infocode', models.AutoField(primary_key=True, serialize=False)),
                ('infovalue', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('created_on', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('modified_on', models.CharField(max_length=100)),
                ('modified_by', models.CharField(max_length=100)),
                ('dev_remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chemical_Master',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_no', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('project_code', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('created_on', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('modified_on', models.CharField(max_length=100)),
                ('modified_by', models.CharField(max_length=100)),
                ('dev_remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Tran',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=100)),
                ('tran_type_IR', models.CharField(max_length=100)),
                ('qnty', models.CharField(max_length=100)),
                ('ref_number', models.CharField(max_length=100)),
                ('ref_type', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('created_on', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('modified_on', models.CharField(max_length=100)),
                ('modified_by', models.CharField(max_length=100)),
                ('dev_remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Master',
            fields=[
                ('project_code', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
    ]
