# Generated by Django 4.1.1 on 2024-02-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appinfo',
            fields=[
                ('infocode', models.AutoField(primary_key=True, serialize=False)),
                ('infovalue', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('created_on', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('modified_on', models.CharField(max_length=100)),
                ('modified_by', models.CharField(max_length=100)),
                ('dev_remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IssuesNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('researcher_name', models.CharField(max_length=100)),
                ('issues_task', models.CharField(max_length=200)),
                ('date_time', models.DateField()),
                ('issue_raised_by', models.CharField(max_length=200)),
                ('issue_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoginCre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_no', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=100, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('m_date', models.DateField()),
                ('supplier', models.CharField(max_length=100)),
                ('master_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('units', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_code', models.IntegerField()),
                ('issue_date', models.CharField(max_length=100, null=True)),
                ('issue_to', models.CharField(max_length=100, null=True)),
                ('quantity_issued', models.IntegerField(null=True)),
                ('quantity_received', models.IntegerField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('remarks', models.CharField(max_length=100)),
                ('created_on', models.CharField(max_length=100, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('modified_on', models.CharField(max_length=100, null=True)),
                ('modified_by', models.CharField(max_length=100, null=True)),
                ('batch_number', models.CharField(max_length=100, null=True)),
                ('dev_remarks', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Master',
            fields=[
                ('project_code', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request_CI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ItemCode', models.CharField(blank=True, max_length=100, null=True)),
                ('ItemType', models.CharField(blank=True, max_length=100, null=True)),
                ('ItemName', models.CharField(blank=True, max_length=100, null=True)),
                ('RequestDate', models.DateField()),
                ('RequestStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('RequestedBy', models.CharField(max_length=100)),
                ('RequestDetails', models.CharField(max_length=100)),
                ('ApprovedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('RequestedTo', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemReturn',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_date', models.DateTimeField()),
                ('quantity_return', models.IntegerField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemreturns', to='app.master')),
            ],
        ),
        migrations.CreateModel(
            name='ItemReceive',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_date', models.DateTimeField()),
                ('quantity_received', models.IntegerField()),
                ('po_number', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=200)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='app.master')),
            ],
        ),
        migrations.CreateModel(
            name='ItemIssue',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField()),
                ('quantity_issued', models.IntegerField()),
                ('issued_to', models.CharField(max_length=100)),
                ('researcher_name', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=200)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='app.master')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='app.project_master')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Tran',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('tran_type_IR', models.CharField(max_length=100)),
                ('i_date', models.DateField()),
                ('supplier', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_issued', models.IntegerField()),
                ('quantity_received', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('ref_number', models.CharField(max_length=100)),
                ('ref_type', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('created_on', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('modified_on', models.CharField(max_length=100)),
                ('modified_by', models.CharField(max_length=100)),
                ('dev_remarks', models.CharField(max_length=100)),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='app.master')),
            ],
        ),
        migrations.CreateModel(
            name='EmpDet',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app.project_master')),
            ],
        ),
    ]
