# Generated by Django 4.1.1 on 2024-02-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReceive',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_date', models.DateTimeField()),
                ('quantity_received', models.IntegerField()),
                ('po_number', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=200)),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='app.master')),
            ],
        ),
        migrations.CreateModel(
            name='ItemIssue',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField()),
                ('quantity_issued', models.IntegerField()),
                ('issued_to', models.CharField(max_length=100)),
                ('researcher_name', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=200)),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='app.master')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='app.project_master')),
            ],
        ),
    ]
