# Generated by Django 4.1.1 on 2024-02-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='project_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='app.project_master'),
        ),
    ]
