# Generated by Django 4.1.1 on 2024-02-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='instruction_specification',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='master',
            name='min_req_stock',
            field=models.IntegerField(default=0),
        ),
    ]
