# Generated by Django 4.1.1 on 2024-02-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_itemreceive_itemissue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemissue',
            old_name='item_code',
            new_name='c_id',
        ),
        migrations.RenameField(
            model_name='itemreceive',
            old_name='item_code',
            new_name='c_id',
        ),
    ]
