# Generated by Django 4.1.1 on 2024-02-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_master_instruction_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='m_date',
            field=models.DateField(null=True),
        ),
    ]
