# Generated by Django 4.1.1 on 2024-02-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_master_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='location_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
