# Generated by Django 4.1.1 on 2024-02-26 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_itemissue_bill_no_itemreceive_bill_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempReceiveItem',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.CharField(default='', max_length=100)),
                ('receipt_date', models.DateTimeField()),
                ('quantity_received', models.IntegerField()),
                ('po_number', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=200)),
                ('deleted', models.IntegerField(default=0, null=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivetemp', to='app.master')),
            ],
        ),
        migrations.CreateModel(
            name='TempIssueItem',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.CharField(default='', max_length=100)),
                ('issue_date', models.DateTimeField()),
                ('quantity_issued', models.IntegerField()),
                ('issued_to', models.CharField(max_length=100)),
                ('researcher_name', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=200)),
                ('deleted', models.IntegerField(default=0, null=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuetemp', to='app.master')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuetemp', to='app.project_master')),
            ],
        ),
    ]
